User.create!([{ :first_name => 'Jerel',
                :last_name => 'Miller',
                :email => 'jerelmiller@gmail.com',
                :password => 'default',
              },
              { :first_name => 'David',
                :last_name => 'Dougherty',
                :email => 'david@epicislife.com',
                :password => 'default',
              }])
